export const GET_ALL_INTERVENTIONS_START = 'GET_ALL_INTERVENTIONS_START';
export const GET_ALL_INTERVENTIONS_SUCCESS = 'GET_ALL_INTERVENTIONS_SUCCESS';
export const GET_ALL_INTERVENTIONS_FAIL = 'GET_ALL_INTERVENTIONS_FAIL';

export const DELETE_INTERVENTION_START = 'DELETE_INTERVENTION_START';
export const DELETE_INTERVENTION_SUCCESS = 'DELETE_INTERVENTION_SUCCESS';
export const DELETE_INTERVENTION_FAIL = 'DELETE_INTERVENTION_FAIL';

export const ADD_INTERVENTION_START = 'ADD_INTERVENTION_START';
export const ADD_INTERVENTION_SUCCESS = 'ADD_INTERVENTION_SUCCESS';
export const ADD_INTERVENTION_FAIL = 'ADD_INTERVENTION_FAIL';

export const EDIT_INTERVENTION_START = 'EDIT_INTERVENTION_START';
export const EDIT_INTERVENTION_SUCCESS = 'EDIT_INTERVENTION_SUCCESS';
export const EDIT_INTERVENTION_FAIL = 'EDIT_INTERVENTION_FAIL';

export const GET_INTERVENTION_BY_ID_START = 'GET_INTERVENTION_BY_ID_START';
export const GET_INTERVENTION_BY_ID_SUCCESS = 'GET_INTERVENTION_BY_ID_SUCCESS';
export const GET_INTERVENTION_BY_ID_FAIL = 'GET_INTERVENTION_BY_ID_FAIL';

export const INPUT_CHANGED = 'INPUT_CHANGED';

export const RESET_STATE = 'RESET_STATE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';